# -*- coding: utf-8 -*-
"""
Module: master_seed_loader.py
Mục đích: Nạp hạt giống toàn bộ 86 văn bản pháp luật nền tảng cốt lõi vào Sổ cái Kho_Can_Cu_Phap_Ly.xlsx.
"""

import os
import sys
import openpyxl
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

from modules.legal_db_sync import HEADERS_14, apply_table_formatting

EXCEL_PATH = os.path.join(BASE_DIR, "Kho_Can_Cu_Phap_Ly.xlsx")

MASTER_SEED_RECORDS = [   {   'linh_vuc': 'Quy hoạch Xây dựng',
        'loai_vb': 'Luật',
        'so_hieu': '47/2024/QH15',
        'trich_yeu': 'Luật Quy hoạch đô thị và nông thôn năm 2024 (Hợp nhất toàn diện)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '26/11/2024',
        'ngay_hl': '01/07/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Quy hoạch đô thị 30/2009/QH12',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2025; hợp nhất quy hoạch đô thị - nông thôn; bãi bỏ giấy phép quy hoạch; '
                       'phân cấp duyệt Tổng mặt bằng 1/500 cho địa phương; căn cứ gói TV-01',
        'tags': 'ALL, QUY_HOACH, TV-01, TV-02, BQP',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=47/2024/QH15'},
    {   'linh_vuc': 'Quy hoạch Xây dựng',
        'loai_vb': 'Luật',
        'so_hieu': '30/2009/QH12',
        'trich_yeu': 'Luật Quy hoạch đô thị năm 2009 (Hết hiệu lực từ 01/07/2025)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '17/06/2009',
        'ngay_hl': '01/01/2010',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Luật Quy hoạch đô thị và nông thôn số 47/2024/QH15',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2025; đồ án đã duyệt trước 01/07/2025 tiếp tục thực hiện đến hết kỳ quy '
                       'hoạch',
        'tags': 'ALL, QUY_HOACH, TV-01, TV-02, BQP, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=30/2009/QH12'},
    {   'linh_vuc': 'Quy hoạch Xây dựng',
        'loai_vb': 'Nghị định',
        'so_hieu': '178/2025/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều của Luật Quy hoạch đô thị và nông thôn năm 2024',
        'co_quan': 'Chính phủ',
        'ngay_bh': '30/06/2025',
        'ngay_hl': '01/07/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 44/2015/NĐ-CP và Nghị định 72/2019/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2025; chuẩn hóa trình tự lập, thẩm định và phê duyệt bản vẽ Tổng mặt bằng '
                       'tỷ lệ 1/500; căn cứ trực tiếp nghiệm thu gói TV-01',
        'tags': 'ALL, QUY_HOACH, TV-01, TV-02, QLDA',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=178/2025/N%C4%90-CP'},
    {   'linh_vuc': 'Quy hoạch Xây dựng',
        'loai_vb': 'Nghị định',
        'so_hieu': '44/2015/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số nội dung về quy hoạch xây dựng (Đã hết hiệu lực)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '06/05/2015',
        'ngay_hl': '30/06/2015',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 178/2025/NĐ-CP từ ngày 01/07/2025',
        'chuyen_tiep': 'Đã hết hiệu lực từ 01/07/2025; đồ án quy hoạch đã phê duyệt trước 01/07/2025 tiếp tục có hiệu '
                       'lực thi hành theo đồ án đã duyệt',
        'tags': 'ALL, QUY_HOACH, TV-01, TV-02, QLDA, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=44/2015/N%C4%90-CP'},
    {   'linh_vuc': 'Quy hoạch Xây dựng',
        'loai_vb': 'Thông tư',
        'so_hieu': '04/2022/TT-BXD',
        'trich_yeu': 'Quy định về hồ sơ nhiệm vụ và đồ án quy hoạch xây dựng, quy hoạch đô thị và nông thôn',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '24/10/2022',
        'ngay_hl': '01/01/2023',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 12/2016/TT-BXD và Thông tư 02/2017/TT-BXD',
        'chuyen_tiep': 'Quy định thành phần hồ sơ bản vẽ, thuyết minh và quy cách đồ án quy hoạch Tổng mặt bằng tỷ lệ '
                       '1/500 gói TV-01',
        'tags': 'QUY_HOACH, TV-01, HO_SO_QUY_HOACH',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=04/2022/TT-BXD'},
    {   'linh_vuc': 'Quy hoạch Xây dựng',
        'loai_vb': 'Thông tư',
        'so_hieu': '20/2019/TT-BXD',
        'trich_yeu': 'Hướng dẫn xác định, quản lý chi phí quy hoạch xây dựng (Đã hết hiệu lực)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '31/12/2019',
        'ngay_hl': '15/02/2020',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Hết hiệu lực từ 01/07/2025 theo Luật Quy hoạch 47/2024/QH15',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2025; hợp đồng tư vấn quy hoạch đã ký trước 01/07/2025 tiếp tục thực '
                       'hiện theo giá hợp đồng đã ký',
        'tags': 'QUY_HOACH, CHI_PHI_QUY_HOACH, DU_TOAN, TV-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=20/2019/TT-BXD'},
    {   'linh_vuc': 'Quy chuẩn Xây dựng',
        'loai_vb': 'Quy chuẩn',
        'so_hieu': 'QCVN 01:2021/BXD',
        'trich_yeu': 'Quy chuẩn kỹ thuật quốc gia về Quy hoạch xây dựng (ban hành kèm Thông tư 01/2021/TT-BXD)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '19/05/2021',
        'ngay_hl': '05/07/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế QCVN 01:2019/BXD ban hành kèm Thông tư 22/2019/TT-BXD',
        'chuyen_tiep': 'Quy chuẩn bắt buộc áp dụng cho gói TV-01 về mật độ xây dựng, khoảng lùi công trình, khoảng '
                       'cách an toàn PCCC, chỉ giới đường đỏ',
        'tags': 'QCVN, QUY_HOACH, TV-01, TV-02, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=QCVN%2001%3A2021/BXD'},
    {   'linh_vuc': 'Khảo sát & Đo đạc',
        'loai_vb': 'Luật',
        'so_hieu': '27/2018/QH14',
        'trich_yeu': 'Luật Đo đạc và bản đồ năm 2018',
        'co_quan': 'Quốc hội',
        'ngay_bh': '14/06/2018',
        'ngay_hl': '01/01/2019',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Căn cứ pháp lý cho công tác đo đạc khảo sát địa hình, trắc địa công trình phục vụ lập quy '
                       'hoạch TV-01 và khảo sát TV-02',
        'tags': 'KHAO_SAT, DO_DAC, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=27/2018/QH14'},
    {   'linh_vuc': 'Khảo sát & Đo đạc',
        'loai_vb': 'Nghị định',
        'so_hieu': '27/2019/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều của Luật Đo đạc và bản đồ',
        'co_quan': 'Chính phủ',
        'ngay_bh': '13/03/2019',
        'ngay_hl': '01/05/2019',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Được sửa đổi, bổ sung bởi Nghị định 136/2021/NĐ-CP',
        'chuyen_tiep': 'Quy định quy chuẩn đo đạc bản đồ địa hình tỷ lệ 1/500 phục vụ lập quy hoạch TMB và thiết kế '
                       'xây dựng',
        'tags': 'KHAO_SAT, DO_DAC, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=27/2019/N%C4%90-CP'},
    {   'linh_vuc': 'Xây dựng & Quản lý dự án',
        'loai_vb': 'Luật',
        'so_hieu': '135/2025/QH15',
        'trich_yeu': 'Luật Xây dựng năm 2025 (Thay thế toàn diện Luật Xây dựng 2014 & Luật 62/2020)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '10/12/2025',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Xây dựng 50/2014/QH13 và Luật 62/2020/QH14',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2026. ĐỘT PHÁ: BÃI BỎ cơ quan chuyên môn thẩm định thiết kế sau TKCS; CĐT '
                       'tự phê duyệt TKBVTC và dự toán qua tư vấn thẩm tra TV-05',
        'tags': 'ALL, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=135/2025/QH15'},
    {   'linh_vuc': 'Xây dựng & Quản lý dự án',
        'loai_vb': 'Luật',
        'so_hieu': '50/2014/QH13',
        'trich_yeu': 'Luật Xây dựng năm 2014 (Hết hiệu lực từ 01/07/2026)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '18/06/2014',
        'ngay_hl': '01/01/2015',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Luật Xây dựng số 135/2025/QH15 từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026; dự án đã duyệt trước 01/07/2026 không phải duyệt lại; nếu điều '
                       'chỉnh sau 01/07/2026 thì thực hiện theo Luật 135/2025',
        'tags': 'ALL, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=50/2014/QH13'},
    {   'linh_vuc': 'Xây dựng & Quản lý dự án',
        'loai_vb': 'Luật',
        'so_hieu': '62/2020/QH14',
        'trich_yeu': 'Luật sửa đổi, bổ sung một số điều của Luật Xây dựng năm 2020 (Hết hiệu lực 01/07/2026)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '17/06/2020',
        'ngay_hl': '01/01/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Luật Xây dựng số 135/2025/QH15 từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026; cơ chế thẩm định thiết kế giai đoạn 2021-2026 chuyển giao sang Chủ '
                       'đầu tư tự phê duyệt theo Luật 135/2025',
        'tags': 'ALL, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=62/2020/QH14'},
    {   'linh_vuc': 'Xây dựng & Quản lý dự án',
        'loai_vb': 'Nghị định',
        'so_hieu': '217/2026/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều của Luật Xây dựng về quản lý hoạt động đầu tư xây dựng',
        'co_quan': 'Chính phủ',
        'ngay_bh': '19/06/2026',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 15/2021/NĐ-CP, Nghị định 175/2024/NĐ-CP và Nghị định 35/2023/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2026; hướng dẫn bãi bỏ thẩm định thiết kế sau TKCS của CQCM; CĐT tự duyệt '
                       'TKBVTC qua tư vấn thẩm tra độc lập TV-05',
        'tags': 'ALL, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=217/2026/N%C4%90-CP'},
    {   'linh_vuc': 'Xây dựng & Quản lý dự án',
        'loai_vb': 'Nghị định',
        'so_hieu': '175/2024/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung một số điều của Nghị định số 15/2021/NĐ-CP về quản lý dự án ĐTXD (Đã hết hiệu '
                     'lực)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '30/12/2024',
        'ngay_hl': '31/12/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 217/2026/NĐ-CP từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026; kết quả thẩm định thiết kế đã có trước 01/07/2026 giữ nguyên giá '
                       'trị pháp lý',
        'tags': 'ALL, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=175/2024/N%C4%90-CP'},
    {   'linh_vuc': 'Xây dựng & Quản lý dự án',
        'loai_vb': 'Nghị định',
        'so_hieu': '15/2021/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số nội dung về quản lý dự án đầu tư xây dựng (Đã hết hiệu lực)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '03/03/2021',
        'ngay_hl': '03/03/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 175/2024/NĐ-CP và Nghị định 217/2026/NĐ-CP',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026; chứng chỉ hành nghề và chứng chỉ năng lực tổ chức đã cấp trước '
                       '01/07/2026 có giá trị đến khi hết hạn',
        'tags': 'ALL, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=15/2021/N%C4%90-CP'},
    {   'linh_vuc': 'Xây dựng & Quản lý dự án',
        'loai_vb': 'Nghị định',
        'so_hieu': '35/2023/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung một số điều của các Nghị định thuộc lĩnh vực quản lý nhà nước của Bộ Xây dựng',
        'co_quan': 'Chính phủ',
        'ngay_bh': '20/06/2023',
        'ngay_hl': '20/06/2023',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Được sửa đổi một phần bởi NĐ 210/2026/NĐ-CP',
        'chuyen_tiep': 'Cắt giảm, đơn giản hóa thủ tục hành chính trong lập quy hoạch và quản lý dự án xây dựng',
        'tags': 'ALL, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=35/2023/N%C4%90-CP'},
    {   'linh_vuc': 'An toàn Lao động',
        'loai_vb': 'Luật',
        'so_hieu': '84/2015/QH13',
        'trich_yeu': 'Luật An toàn, vệ sinh lao động năm 2015',
        'co_quan': 'Quốc hội',
        'ngay_bh': '25/06/2015',
        'ngay_hl': '01/07/2016',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Quy định biện pháp an toàn lao động bắt buộc trên công trường thi công xây dựng (XD-01) và '
                       'giám sát (TV-08)',
        'tags': 'AN_TOAN_LAO_DONG, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=84/2015/QH13'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Luật',
        'so_hieu': '22/2023/QH15',
        'trich_yeu': 'Luật Đấu thầu năm 2023',
        'co_quan': 'Quốc hội',
        'ngay_bh': '23/06/2023',
        'ngay_hl': '01/01/2024',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Đấu thầu 43/2013/QH13',
        'chuyen_tiep': 'Luật đấu thầu nền tảng chi phối toàn bộ 11 gói thầu TV, XD, PTV của dự án trên Hệ thống mạng '
                       'đấu thầu quốc gia',
        'tags': 'ALL, DAU_THAU, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=22/2023/QH15'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Luật',
        'so_hieu': '57/2024/QH15',
        'trich_yeu': 'Luật sửa đổi, bổ sung một số điều của Luật Quy hoạch, Luật Đầu tư, Luật PPP và Luật Đấu thầu',
        'co_quan': 'Quốc hội',
        'ngay_bh': '29/11/2024',
        'ngay_hl': '15/01/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi, bổ sung Luật Đấu thầu 22/2023/QH15',
        'chuyen_tiep': 'Mở rộng phân cấp thẩm quyền chỉ định thầu, rút ngắn thời gian chuẩn bị E-HSDT và mua sắm công',
        'tags': 'ALL, DAU_THAU, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=57/2024/QH15'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Luật',
        'so_hieu': '90/2025/QH15',
        'trich_yeu': 'Luật sửa đổi, bổ sung một số điều của Luật Đấu thầu, Luật Đầu tư công, Luật Quản lý TSC',
        'co_quan': 'Quốc hội',
        'ngay_bh': '25/06/2025',
        'ngay_hl': '01/07/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi Luật Đấu thầu 22/2023/QH15',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2025; nâng hạn mức chỉ định thầu rút gọn (500 triệu gói TV/PTV, 01 tỷ gói '
                       'XD); phân cấp triệt để CĐT duyệt E-HSMT',
        'tags': 'ALL, DAU_THAU, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=90/2025/QH15'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Luật',
        'so_hieu': '43/2013/QH13',
        'trich_yeu': 'Luật Đấu thầu năm 2013 (Đã hết hiệu lực từ 01/01/2024)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '26/11/2013',
        'ngay_hl': '01/07/2014',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Luật Đấu thầu 22/2023/QH15',
        'chuyen_tiep': 'Hết hiệu lực từ 01/01/2024; gói thầu phát hành HSMT trước 01/01/2024 tiếp tục thực hiện theo '
                       'Luật 43/2013 đến khi quyết toán',
        'tags': 'ALL, DAU_THAU, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=43/2013/QH13'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Nghị định',
        'so_hieu': '214/2025/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều và biện pháp thi hành Luật Đấu thầu về lựa chọn nhà thầu',
        'co_quan': 'Chính phủ',
        'ngay_bh': '04/08/2025',
        'ngay_hl': '04/08/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 24/2024/NĐ-CP và Nghị định 63/2014/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 04/08/2025; nâng hạn mức chỉ định thầu rút gọn (xây lắp 2 tỷ, mua sắm 500tr); '
                       'bãi bỏ thẩm định KHLCNT tổng thể',
        'tags': 'ALL, DAU_THAU, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=214/2025/N%C4%90-CP'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Nghị định',
        'so_hieu': '24/2024/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết thi hành Luật Đấu thầu về lựa chọn nhà thầu (Đã hết hiệu lực)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '27/02/2024',
        'ngay_hl': '27/02/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 214/2025/NĐ-CP từ ngày 04/08/2025',
        'chuyen_tiep': 'Hết hiệu lực từ 04/08/2025; áp dụng chuyển tiếp cho các gói thầu đã phát hành E-HSMT trước '
                       '04/08/2025',
        'tags': 'ALL, DAU_THAU, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=24/2024/N%C4%90-CP'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Nghị định',
        'so_hieu': '63/2014/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết thi hành một số điều của Luật Đấu thầu (Đã hết hiệu lực)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '26/06/2014',
        'ngay_hl': '15/08/2014',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 24/2024/NĐ-CP',
        'chuyen_tiep': 'Hết hiệu lực từ 27/02/2024',
        'tags': 'ALL, DAU_THAU, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=63/2014/N%C4%90-CP'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Thông tư',
        'so_hieu': '79/2025/TT-BTC',
        'trich_yeu': 'Hướng dẫn việc cung cấp, đăng tải thông tin về đấu thầu và mẫu hồ sơ đấu thầu trên e-GP',
        'co_quan': 'Bộ Tài chính',
        'ngay_bh': '20/07/2025',
        'ngay_hl': '04/08/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 06/2024/TT-BKHĐT và Thông tư 22/2024/TT-BKHĐT',
        'chuyen_tiep': 'Có hiệu lực từ 04/08/2025; ban hành toàn bộ biểu mẫu E-HSMT xây lắp, tư vấn (TV-04, TV-06, '
                       'XD-01) trên Hệ thống e-GP',
        'tags': 'ALL, DAU_THAU, E_HSMT, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=79/2025/TT-BTC'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Thông tư',
        'so_hieu': '06/2024/TT-BKHĐT',
        'trich_yeu': 'Hướng dẫn đăng tải thông tin và mẫu hồ sơ đấu thầu trên e-GP (Đã hết hiệu lực)',
        'co_quan': 'Bộ Kế hoạch và Đầu tư',
        'ngay_bh': '26/04/2024',
        'ngay_hl': '26/04/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 79/2025/TT-BTC',
        'chuyen_tiep': 'Hết hiệu lực từ 04/08/2025',
        'tags': 'ALL, DAU_THAU, E_HSMT, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=06/2024/TT-BKH%C4%90T'},
    {   'linh_vuc': 'Đấu thầu qua mạng',
        'loai_vb': 'Thông tư',
        'so_hieu': '80/2025/TT-BTC',
        'trich_yeu': 'Quy định chi tiết mẫu hồ sơ yêu cầu, báo cáo đánh giá trong lựa chọn nhà thầu mua sắm công',
        'co_quan': 'Bộ Tài chính',
        'ngay_bh': '22/07/2025',
        'ngay_hl': '08/08/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 07/2024/TT-BKHĐT và Thông tư 23/2024/TT-BKHĐT',
        'chuyen_tiep': 'Có hiệu lực từ 08/08/2025; áp dụng lập HSYC và đánh giá hồ sơ đề xuất gói thầu mua sắm hàng '
                       'hóa, doanh cụ',
        'tags': 'ALL, DAU_THAU, E_HSMT, TV-06, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=80/2025/TT-BTC'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Nghị định',
        'so_hieu': '206/2026/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều của Luật Xây dựng về quản lý chi phí đầu tư xây dựng',
        'co_quan': 'Chính phủ',
        'ngay_bh': '15/06/2026',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 10/2021/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2026; chuẩn hóa 4 phương pháp lập TMĐT; trao quyền cho Chủ đầu tư tự phê '
                       'duyệt dự toán chi phí chuẩn bị đầu tư và dự toán gói thầu',
        'tags': 'ALL, DU_TOAN, QUAN_LY_CHI_PHI, TV-01, TV-02, TV-03, TV-04, TV-05, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=206/2026/N%C4%90-CP'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Nghị định',
        'so_hieu': '10/2021/NĐ-CP',
        'trich_yeu': 'Về quản lý chi phí đầu tư xây dựng (Hết hiệu lực từ 01/07/2026)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '09/02/2021',
        'ngay_hl': '09/02/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 206/2026/NĐ-CP từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026; dự án đã phê duyệt dự toán trước 01/07/2026 thực hiện theo điều '
                       'khoản chuyển tiếp của NĐ 206',
        'tags': 'ALL, DU_TOAN, QUAN_LY_CHI_PHI, TV-01, TV-02, TV-03, TV-04, TV-05, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=10/2021/N%C4%90-CP'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '36/2026/TT-BXD',
        'trich_yeu': 'Hướng dẫn một số nội dung xác định và quản lý chi phí đầu tư xây dựng',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '24/06/2026',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 11/2021/TT-BXD, Thông tư 14/2023/TT-BXD và Thông tư 01/2025/TT-BXD',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2026; quy định cơ cấu chi phí xây dựng, phương pháp tính chi phí gián '
                       'tiếp và chi phí chung trong dự toán mới nhất',
        'tags': 'ALL, DU_TOAN, QUAN_LY_CHI_PHI, TV-01, TV-02, TV-03, TV-04, TV-05, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=36/2026/TT-BXD'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '38/2026/TT-BXD',
        'trich_yeu': 'Ban hành hệ thống định mức dự toán xây dựng công trình và định mức chi phí tư vấn đầu tư xây '
                     'dựng',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '26/06/2026',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 12/2021/TT-BXD và Thông tư 09/2024/TT-BXD',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2026; ban hành hệ thống định mức dự toán mới và tỷ lệ % chi phí tư vấn '
                       'lập BCNCKT (TV-03), TKBVTC (TV-04), thẩm tra (TV-05), giám sát (TV-08), kiểm toán (TV-09)',
        'tags': 'ALL, DINH_MUC, DU_TOAN, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-08, TV-09, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=38/2026/TT-BXD'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '12/2021/TT-BXD',
        'trich_yeu': 'Ban hành định mức xây dựng (Hết hiệu lực từ 01/07/2026)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '31/08/2021',
        'ngay_hl': '15/10/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 38/2026/TT-BXD từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026',
        'tags': 'ALL, DINH_MUC, DU_TOAN, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=12/2021/TT-BXD'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '09/2024/TT-BXD',
        'trich_yeu': 'Sửa đổi, bổ sung một số định mức xây dựng ban hành tại Thông tư số 12/2021/TT-BXD (Hết hiệu lực '
                     '01/07/2026)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '30/08/2024',
        'ngay_hl': '15/10/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 38/2026/TT-BXD',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026',
        'tags': 'ALL, DINH_MUC, DU_TOAN, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=09/2024/TT-BXD'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '01/2025/TT-BXD',
        'trich_yeu': 'Sửa đổi, bổ sung Thông tư 11/2021/TT-BXD về quản lý chi phí (Hết hiệu lực 01/07/2026)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '15/01/2025',
        'ngay_hl': '01/03/2025',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 36/2026/TT-BXD',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026',
        'tags': 'ALL, DU_TOAN, QUAN_LY_CHI_PHI, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=01/2025/TT-BXD'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '11/2021/TT-BXD',
        'trich_yeu': 'Hướng dẫn xác định và quản lý chi phí đầu tư xây dựng (Hết hiệu lực từ 01/07/2026)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '31/08/2021',
        'ngay_hl': '15/10/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 36/2026/TT-BXD từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026',
        'tags': 'ALL, DU_TOAN, QUAN_LY_CHI_PHI, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=11/2021/TT-BXD'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '14/2023/TT-BXD',
        'trich_yeu': 'Sửa đổi, bổ sung Thông tư số 11/2021/TT-BXD về quản lý chi phí (Hết hiệu lực 01/07/2026)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '29/12/2023',
        'ngay_hl': '15/02/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 36/2026/TT-BXD từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026',
        'tags': 'ALL, DU_TOAN, QUAN_LY_CHI_PHI, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=14/2023/TT-BXD'},
    {   'linh_vuc': 'Chi phí & Định mức',
        'loai_vb': 'Thông tư',
        'so_hieu': '13/2021/TT-BXD',
        'trich_yeu': 'Hướng dẫn phương pháp xác định các chỉ tiêu kinh tế kỹ thuật và đo bóc khối lượng công trình',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '31/08/2021',
        'ngay_hl': '15/10/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Quy chuẩn phương pháp đo bóc khối lượng phục vụ lập dự toán và nghiệm thu công trình',
        'tags': 'ALL, DU_TOAN, DO_BOC_KHOI_LUONG, TV-04, TV-05, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=13/2021/TT-BXD'},
    {   'linh_vuc': 'Suất vốn đầu tư',
        'loai_vb': 'Quyết định',
        'so_hieu': '425/QĐ-BXD',
        'trich_yeu': 'Công bố Suất vốn đầu tư xây dựng công trình và giá xây dựng tổng hợp bộ phận kết cấu công trình',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '30/03/2026',
        'ngay_hl': '30/03/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Quyết định 510/QĐ-BXD',
        'chuyen_tiep': 'Ban hành ngày 30/03/2026; căn cứ tính Tổng mức đầu tư Báo cáo NCKT (gói TV-02, TV-03)',
        'tags': 'SUAT_VON_DAU_TU, TMDT, TV-01, TV-02, TV-03, TV-04',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=425/Q%C4%90-BXD'},
    {   'linh_vuc': 'Suất vốn đầu tư',
        'loai_vb': 'Quyết định',
        'so_hieu': '510/QĐ-BXD',
        'trich_yeu': 'Công bố Suất vốn đầu tư xây dựng công trình và giá xây dựng tổng hợp năm 2023 (Hết hiệu lực)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '19/05/2024',
        'ngay_hl': '19/05/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Quyết định 425/QĐ-BXD',
        'chuyen_tiep': 'Hết hiệu lực',
        'tags': 'SUAT_VON_DAU_TU, TMDT, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=510/Q%C4%90-BXD'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '101/2026/TT-BQP',
        'trich_yeu': 'Quy định chi tiết và biện pháp thực hiện một số nội dung Luật Xây dựng thuộc phạm vi Bộ Quốc '
                     'phòng',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '09/07/2026',
        'ngay_hl': '09/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 106/2021/TT-BQP',
        'chuyen_tiep': 'Có hiệu lực từ 09/07/2026; hướng dẫn chi tiết quy chuẩn xây dựng công trình quốc phòng, thẩm '
                       'quyền kiểm tra nghiệm thu của Cục Doanh trại, kiểm tra trực tuyến và ứng dụng BIM',
        'tags': 'ALL, BQP, QLDA, XD-01, TOAN_QUAN',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=101/2026/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '102/2026/TT-BQP',
        'trich_yeu': 'Quy định về lập, thẩm định, quyết định, phân cấp quyết định chủ trương và dự án đầu tư trong BQP',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '17/07/2026',
        'ngay_hl': '17/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 128/2021/TT-BQP, Thông tư 73/2023/TT-BQP và Thông tư 120/2024/TT-BQP',
        'chuyen_tiep': 'Có hiệu lực từ 17/07/2026; phân cấp toàn diện chủ trương đầu tư, thẩm định BCNCKT, phê duyệt '
                       'KHLCNT và phê duyệt dự toán cho Tư lệnh/Chủ đầu tư theo từng hạn mức nhóm dự án',
        'tags': 'ALL, BQP, PHAN_CAP, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=102/2026/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '128/2021/TT-BQP',
        'trich_yeu': 'Quy định phân cấp, ủy quyền chủ trương và dự án đầu tư công trong BQP (Hết hiệu lực 17/07/2026)',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '01/10/2021',
        'ngay_hl': '20/11/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 101/2026/TT-BQP và Thông tư 102/2026/TT-BQP',
        'chuyen_tiep': 'Hết hiệu lực từ 17/07/2026; dự án đã duyệt chủ trương hoặc đang thẩm định trước 17/07/2026 '
                       'tiếp tục áp dụng TT 128',
        'tags': 'ALL, BQP, PHAN_CAP, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=128/2021/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '73/2023/TT-BQP',
        'trich_yeu': 'Sửa đổi Thông tư 128/2021/TT-BQP về phân cấp đầu tư công BQP (Hết hiệu lực 17/07/2026)',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '05/10/2023',
        'ngay_hl': '20/11/2023',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 102/2026/TT-BQP',
        'chuyen_tiep': 'Hết hiệu lực từ 17/07/2026',
        'tags': 'ALL, BQP, PHAN_CAP, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=73/2023/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '120/2024/TT-BQP',
        'trich_yeu': 'Sửa đổi Thông tư 128/2021/TT-BQP về phân cấp dự án đầu tư công BQP (Hết hiệu lực 17/07/2026)',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '26/12/2024',
        'ngay_hl': '10/02/2025',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Thông tư 102/2026/TT-BQP',
        'chuyen_tiep': 'Hết hiệu lực từ 17/07/2026',
        'tags': 'ALL, BQP, PHAN_CAP, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=120/2024/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '174/2021/TT-BQP',
        'trich_yeu': 'Quy định về quản lý chất lượng, thi công xây dựng và bảo trì công trình trong Bộ Quốc phòng',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '27/12/2021',
        'ngay_hl': '12/02/2022',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Được sửa đổi, bổ sung bởi Thông tư 24/2025/TT-BQP',
        'chuyen_tiep': 'Quy chuẩn nghiệm thu và quản lý chất lượng công trình quân sự (áp dụng song song phần sửa đổi '
                       'của TT 24/2025)',
        'tags': 'CHAT_LUONG, NGHIEM_THU, TV-01, TV-02, TV-04, TV-05, TV-07, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=174/2021/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '24/2025/TT-BQP',
        'trich_yeu': 'Sửa đổi, bổ sung Thông tư số 174/2021/TT-BQP về quản lý chất lượng công trình trong Bộ Quốc '
                     'phòng',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '06/05/2025',
        'ngay_hl': '20/06/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi, bổ sung Thông tư 174/2021/TT-BQP',
        'chuyen_tiep': 'Có hiệu lực từ 20/06/2025; bãi bỏ Điều 4, 6, 7; thay thế các biểu mẫu nghiệm thu mới và phân '
                       'loại công trình quốc phòng Loại A, Loại B',
        'tags': 'CHAT_LUONG, NGHIEM_THU, TV-01, TV-02, TV-04, TV-05, TV-07, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=24/2025/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '36/2023/TT-BQP',
        'trich_yeu': 'Ban hành Điều lệ Doanh trại Quân đội nhân dân Việt Nam',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '29/05/2023',
        'ngay_hl': '13/07/2023',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Điều lệ Doanh trại QĐNDVN năm 2002',
        'chuyen_tiep': 'Có hiệu lực từ 13/07/2023; điều lệ 10 chương, 60 điều chi phối toàn diện quy hoạch tổng mặt '
                       'bằng, bảo dưỡng, quản lý và sử dụng doanh trại',
        'tags': 'BQP, DOANH_TRAI, TV-01, TV-02, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=36/2023/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '150/2018/TT-BQP',
        'trich_yeu': 'Quy định tiêu chuẩn, định mức sử dụng máy móc, thiết bị văn phòng trong Bộ Quốc phòng',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '11/10/2018',
        'ngay_hl': '26/11/2018',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Quyết định 162/2002/QĐ-BQP',
        'chuyen_tiep': 'Tiêu chuẩn định mức máy móc, thiết bị làm việc của cán bộ sĩ quan BQP (áp dụng trực tiếp cho '
                       'gói Doanh cụ XD-01)',
        'tags': 'BQP, DOANH_TRAI, TV-01, TV-02, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=150/2018/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Thông tư',
        'so_hieu': '94/2024/TT-BQP',
        'trich_yeu': 'Quy định chi tiết một số điều của Luật Nhà ở áp dụng trong Bộ Quốc phòng',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '11/11/2024',
        'ngay_hl': '26/12/2024',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Áp dụng cho các dự án đầu tư xây dựng nhà ở công vụ và nhà ở cho lực lượng vũ trang thuộc BQP',
        'tags': 'BQP, DOANH_TRAI, TV-01, TV-02, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=94/2024/TT-BQP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Quyết định',
        'so_hieu': '35/QĐ-TTg',
        'trich_yeu': 'Ban hành Danh mục bí mật Nhà nước trong lĩnh vực Quốc phòng',
        'co_quan': 'Thủ tướng Chính phủ',
        'ngay_bh': '11/03/2025',
        'ngay_hl': '11/03/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Quyết định số 12/QĐ-TTg',
        'chuyen_tiep': 'Quy định bảo mật hồ sơ, tài liệu thiết kế công trình quân sự',
        'tags': 'ALL, BQP, PHAN_CAP, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=35/Q%C4%90-TTg'},
    {   'linh_vuc': 'Chất lượng & Nghiệm thu',
        'loai_vb': 'Nghị định',
        'so_hieu': '207/2026/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số nội dung về quản lý chất lượng, thi công xây dựng và bảo trì công trình',
        'co_quan': 'Chính phủ',
        'ngay_bh': '18/06/2026',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 06/2021/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2026; bắt buộc áp dụng Nhật ký thi công điện tử, số hóa biên bản nghiệm '
                       'thu; phân cấp kiểm tra công tác nghiệm thu đưa công trình vào sử dụng (TV-08, XD-01)',
        'tags': 'CHAT_LUONG, NGHIEM_THU, TV-01, TV-02, TV-04, TV-05, TV-07, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=207/2026/N%C4%90-CP'},
    {   'linh_vuc': 'Chất lượng & Nghiệm thu',
        'loai_vb': 'Nghị định',
        'so_hieu': '06/2021/NĐ-CP',
        'trich_yeu': 'Quy định về quản lý chất lượng, thi công và bảo trì công trình (Hết hiệu lực 01/07/2026)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '26/01/2021',
        'ngay_hl': '26/01/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 207/2026/NĐ-CP từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026; biên bản nghiệm thu đã lập theo NĐ 06/2021 trước 01/07/2026 giữ '
                       'nguyên giá trị pháp lý',
        'tags': 'CHAT_LUONG, NGHIEM_THU, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=06/2021/N%C4%90-CP'},
    {   'linh_vuc': 'Chất lượng & Nghiệm thu',
        'loai_vb': 'Thông tư',
        'so_hieu': '10/2021/TT-BXD',
        'trich_yeu': 'Hướng dẫn một số điều và biện pháp thi hành Nghị định số 06/2021/NĐ-CP và Nghị định số '
                     '15/2021/NĐ-CP',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '25/08/2021',
        'ngay_hl': '15/10/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Quy chuẩn đánh giá an toàn công trình, kiểm định và lập danh mục hồ sơ hoàn thành công trình '
                       '(áp dụng phần còn phù hợp)',
        'tags': 'CHAT_LUONG, NGHIEM_THU, TV-01, TV-02, TV-04, TV-05, TV-07, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=10/2021/TT-BXD'},
    {   'linh_vuc': 'Hợp đồng Xây dựng',
        'loai_vb': 'Nghị định',
        'so_hieu': '210/2026/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết về hợp đồng xây dựng',
        'co_quan': 'Chính phủ',
        'ngay_bh': '15/06/2026',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 37/2015/NĐ-CP và Nghị định 50/2021/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2026; tạm ứng tối thiểu 10% tối đa 50%; điều chỉnh giá hợp đồng trọn gói; '
                       'giải quyết tranh chấp qua Ban xử lý tranh chấp và Hòa giải viên',
        'tags': 'ALL, HOP_DONG, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=210/2026/N%C4%90-CP'},
    {   'linh_vuc': 'Hợp đồng Xây dựng',
        'loai_vb': 'Nghị định',
        'so_hieu': '37/2015/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết về hợp đồng xây dựng (Hết hiệu lực từ 01/07/2026)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '22/04/2015',
        'ngay_hl': '15/06/2015',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 210/2026/NĐ-CP từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026; hợp đồng đã ký trước 01/07/2026 tiếp tục thực hiện theo điều khoản '
                       'hợp đồng đã ký',
        'tags': 'ALL, HOP_DONG, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=37/2015/N%C4%90-CP'},
    {   'linh_vuc': 'Hợp đồng Xây dựng',
        'loai_vb': 'Nghị định',
        'so_hieu': '50/2021/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung Nghị định số 37/2015/NĐ-CP về hợp đồng xây dựng (Hết hiệu lực 01/07/2026)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '01/04/2021',
        'ngay_hl': '01/04/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 210/2026/NĐ-CP từ ngày 01/07/2026',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2026',
        'tags': 'ALL, HOP_DONG, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=50/2021/N%C4%90-CP'},
    {   'linh_vuc': 'Hợp đồng Xây dựng',
        'loai_vb': 'Thông tư',
        'so_hieu': '02/2023/TT-BXD',
        'trich_yeu': 'Hướng dẫn một số nội dung về hợp đồng xây dựng',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '03/03/2023',
        'ngay_hl': '20/04/2023',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Ban hành mẫu hợp đồng tư vấn thiết kế, tư vấn giám sát và hợp đồng thi công xây dựng (lưu ý '
                       'đối chiếu NĐ 210/2026)',
        'tags': 'ALL, HOP_DONG, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=02/2023/TT-BXD'},
    {   'linh_vuc': 'Tiêu chuẩn Kỹ thuật',
        'loai_vb': 'Tiêu chuẩn',
        'so_hieu': 'TCVN 9393:2012',
        'trich_yeu': 'Cọc - Phương pháp thử nghiệm hiện trường bằng tải trọng tĩnh ép dọc trục',
        'co_quan': 'Bộ Khoa học và Công nghệ',
        'ngay_bh': '28/12/2012',
        'ngay_hl': '28/12/2012',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế TCXDVN 269:2002',
        'chuyen_tiep': 'Tiêu chuẩn kỹ thuật bắt buộc áp dụng cho gói thầu TV-07 Thí nghiệm nén tĩnh cọc',
        'tags': 'THI_NGHIEM_COC, TV-07, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=TCVN%209393%3A2012'},
    {   'linh_vuc': 'Tiêu chuẩn Kỹ thuật',
        'loai_vb': 'Tiêu chuẩn',
        'so_hieu': 'TCVN 9363:2012',
        'trich_yeu': 'Khảo sát địa chất công trình cho nhà cao tầng',
        'co_quan': 'Bộ Khoa học và Công nghệ',
        'ngay_bh': '28/12/2012',
        'ngay_hl': '28/12/2012',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Tiêu chuẩn kỹ thuật cho công tác khoan khảo sát địa chất gói TV-02',
        'tags': 'KHAO_SAT, TV-02',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=TCVN%209363%3A2012'},
    {   'linh_vuc': 'Tiêu chuẩn Kỹ thuật',
        'loai_vb': 'Tiêu chuẩn',
        'so_hieu': 'TCVN 9401:2012',
        'trich_yeu': 'Kỹ thuật đo và xử lý số liệu GPS trong trắc địa công trình',
        'co_quan': 'Bộ Khoa học và Công nghệ',
        'ngay_bh': '28/12/2012',
        'ngay_hl': '28/12/2012',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Tiêu chuẩn kỹ thuật cho công tác đo đạc địa hình, định vị công trình gói TV-01',
        'tags': 'DO_DAC, TV-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=TCVN%209401%3A2012'},
    {   'linh_vuc': 'Bảo hiểm Xây dựng',
        'loai_vb': 'Luật',
        'so_hieu': '08/2022/QH15',
        'trich_yeu': 'Luật Kinh doanh bảo hiểm năm 2022',
        'co_quan': 'Quốc hội',
        'ngay_bh': '16/06/2022',
        'ngay_hl': '01/01/2023',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Kinh doanh bảo hiểm 2000',
        'chuyen_tiep': 'Luật nền tảng điều chỉnh hoạt động bảo hiểm công trình xây dựng (gói PTV-01)',
        'tags': 'BAO_HIEM, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=08/2022/QH15'},
    {   'linh_vuc': 'Bảo hiểm Xây dựng',
        'loai_vb': 'Nghị định',
        'so_hieu': '67/2023/NĐ-CP',
        'trich_yeu': 'Quy định về bảo hiểm bắt buộc trong hoạt động đầu tư xây dựng',
        'co_quan': 'Chính phủ',
        'ngay_bh': '06/09/2023',
        'ngay_hl': '06/09/2023',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 119/2015/NĐ-CP',
        'chuyen_tiep': 'Nghị định chi phối biểu phí và điều kiện bảo hiểm công trình trong thời gian thi công (gói '
                       'PTV-01)',
        'tags': 'BAO_HIEM, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=67/2023/N%C4%90-CP'},
    {   'linh_vuc': 'Kiểm toán Độc lập',
        'loai_vb': 'Luật',
        'so_hieu': '67/2011/QH12',
        'trich_yeu': 'Luật Kiểm toán độc lập năm 2011',
        'co_quan': 'Quốc hội',
        'ngay_bh': '29/03/2011',
        'ngay_hl': '01/01/2012',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Căn cứ pháp lý then chốt cho gói TV-09 Kiểm toán độc lập quyết toán vốn đầu tư hoàn thành',
        'tags': 'KIEM_TOAN, TV-09',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=67/2011/QH12'},
    {   'linh_vuc': 'Kiểm toán Độc lập',
        'loai_vb': 'Thông tư',
        'so_hieu': '67/2015/TT-BTC',
        'trich_yeu': 'Ban hành Chuẩn mực kiểm toán Việt Nam số 1000 - Kiểm toán quyết toán dự án hoàn thành (VSA 1000)',
        'co_quan': 'Bộ Tài chính',
        'ngay_bh': '08/05/2015',
        'ngay_hl': '01/01/2016',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Quy chuẩn phương pháp kiểm toán báo cáo quyết toán dự án hoàn thành gói TV-09',
        'tags': 'KIEM_TOAN, TV-09',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=67/2015/TT-BTC'},
    {   'linh_vuc': 'Đầu tư công',
        'loai_vb': 'Luật',
        'so_hieu': '58/2024/QH15',
        'trich_yeu': 'Luật Đầu tư công năm 2024',
        'co_quan': 'Quốc hội',
        'ngay_bh': '29/11/2024',
        'ngay_hl': '01/01/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Đầu tư công 39/2019/QH14',
        'chuyen_tiep': 'Quy định thẩm quyền quyết định chủ trương đầu tư, phân cấp quản lý dự án sử dụng vốn ngân sách '
                       'nhà nước',
        'tags': 'ALL, DAU_TU_CONG, CHU_TRUONG, TV-01, TV-02, TV-03, TV-09',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=58/2024/QH15'},
    {   'linh_vuc': 'Đầu tư công',
        'loai_vb': 'Luật',
        'so_hieu': '39/2019/QH14',
        'trich_yeu': 'Luật Đầu tư công năm 2019 (Đã hết hiệu lực từ 01/01/2025)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '13/06/2019',
        'ngay_hl': '01/01/2020',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Luật Đầu tư công 58/2024/QH15',
        'chuyen_tiep': 'Hết hiệu lực từ 01/01/2025',
        'tags': 'ALL, DAU_TU_CONG, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=39/2019/QH14'},
    {   'linh_vuc': 'Đầu tư công',
        'loai_vb': 'Nghị định',
        'so_hieu': '40/2020/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết thi hành một số điều của Luật Đầu tư công',
        'co_quan': 'Chính phủ',
        'ngay_bh': '06/04/2020',
        'ngay_hl': '06/04/2020',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Quy định trình tự, thủ tục lập và giao kế hoạch đầu tư công trung hạn và hàng năm',
        'tags': 'ALL, DAU_TU_CONG, TV-01, TV-02, TV-03',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=40/2020/N%C4%90-CP'},
    {   'linh_vuc': 'Quyết toán vốn',
        'loai_vb': 'Nghị định',
        'so_hieu': '254/2025/NĐ-CP',
        'trich_yeu': 'Quy định về quản lý, thanh toán, quyết toán dự án sử dụng vốn đầu tư công',
        'co_quan': 'Chính phủ',
        'ngay_bh': '26/09/2025',
        'ngay_hl': '26/09/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 99/2021/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 26/09/2025; rút ngắn thời gian thanh toán KBNN còn 02 ngày làm việc; hạn lập hồ '
                       'sơ quyết toán A-B không quá 06 tháng nhóm C (TV-09, XD-01)',
        'tags': 'ALL, QUYET_TOAN, TAI_CHINH, TV-09, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=254/2025/N%C4%90-CP'},
    {   'linh_vuc': 'Quyết toán vốn',
        'loai_vb': 'Nghị định',
        'so_hieu': '99/2021/NĐ-CP',
        'trich_yeu': 'Quy định quản lý, thanh quyết toán vốn đầu tư công (Hết hiệu lực từ 26/09/2025)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '11/11/2021',
        'ngay_hl': '01/01/2022',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 254/2025/NĐ-CP từ ngày 26/09/2025',
        'chuyen_tiep': 'Hết hiệu lực từ 26/09/2025; hồ sơ quyết toán đã nộp trước 26/09/2025 tiếp tục thẩm tra theo NĐ '
                       '99/2021',
        'tags': 'ALL, QUYET_TOAN, TAI_CHINH, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=99/2021/N%C4%90-CP'},
    {   'linh_vuc': 'Quyết toán vốn',
        'loai_vb': 'Thông tư',
        'so_hieu': '96/2021/TT-BTC',
        'trich_yeu': 'Quy định về hệ thống mẫu biểu hồ sơ quyết toán vốn đầu tư công dự án hoàn thành',
        'co_quan': 'Bộ Tài chính',
        'ngay_bh': '11/11/2021',
        'ngay_hl': '01/01/2022',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Được sửa đổi, bổ sung bởi Thông tư 24/2024/TT-BTC',
        'chuyen_tiep': 'Ban hành toàn bộ mẫu biểu Báo cáo quyết toán A-B, Báo cáo quyết toán hoàn thành',
        'tags': 'ALL, QUYET_TOAN, TAI_CHINH, TV-09, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=96/2021/TT-BTC'},
    {   'linh_vuc': 'Quyết toán vốn',
        'loai_vb': 'Thông tư',
        'so_hieu': '24/2024/TT-BTC',
        'trich_yeu': 'Sửa đổi, bổ sung Thông tư số 96/2021/TT-BTC về mẫu biểu quyết toán vốn đầu tư công',
        'co_quan': 'Bộ Tài chính',
        'ngay_bh': '19/04/2024',
        'ngay_hl': '05/06/2024',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi Thông tư 96/2021/TT-BTC',
        'chuyen_tiep': 'Cập nhật quy trình kiểm toán độc lập và thẩm tra quyết toán vốn đầu tư công hiện hành',
        'tags': 'ALL, QUYET_TOAN, TAI_CHINH, TV-09, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=24/2024/TT-BTC'},
    {   'linh_vuc': 'Phòng cháy chữa cháy',
        'loai_vb': 'Nghị định',
        'so_hieu': '105/2025/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều và biện pháp thi hành Luật Phòng cháy, chữa cháy và cứu nạn, cứu '
                     'hộ',
        'co_quan': 'Chính phủ',
        'ngay_bh': '25/06/2025',
        'ngay_hl': '01/07/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 136/2020/NĐ-CP và Nghị định 50/2024/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 01/07/2025; cắt giảm danh mục thẩm duyệt PCCC; phân cấp Công an huyện/tỉnh; nộp '
                       'trực tuyến DVC (05-07 ngày làm việc)',
        'tags': 'PCCC, TV-02, TV-03, TV-04, TV-05, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=105/2025/N%C4%90-CP'},
    {   'linh_vuc': 'Phòng cháy chữa cháy',
        'loai_vb': 'Nghị định',
        'so_hieu': '136/2020/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết thi hành Luật Phòng cháy và chữa cháy (Hết hiệu lực 01/07/2025)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '24/11/2020',
        'ngay_hl': '10/01/2021',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 105/2025/NĐ-CP từ ngày 01/07/2025',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2025',
        'tags': 'PCCC, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=136/2020/N%C4%90-CP'},
    {   'linh_vuc': 'Phòng cháy chữa cháy',
        'loai_vb': 'Nghị định',
        'so_hieu': '50/2024/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung Nghị định số 136/2020/NĐ-CP về PCCC (Hết hiệu lực 01/07/2025)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '10/05/2024',
        'ngay_hl': '15/05/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 105/2025/NĐ-CP',
        'chuyen_tiep': 'Hết hiệu lực từ 01/07/2025',
        'tags': 'PCCC, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=50/2024/N%C4%90-CP'},
    {   'linh_vuc': 'Quy chuẩn PCCC',
        'loai_vb': 'Quy chuẩn',
        'so_hieu': 'QCVN 06:2022/BXD',
        'trich_yeu': 'Quy chuẩn kỹ thuật quốc gia về An toàn cháy cho nhà và công trình (ban hành kèm Thông tư '
                     '06/2022/TT-BXD)',
        'co_quan': 'Bộ Xây dựng',
        'ngay_bh': '30/11/2022',
        'ngay_hl': '16/01/2023',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Được sửa đổi bởi Thông tư 09/2023/TT-BXD (Sửa đổi 1:2023 QCVN 06:2022/BXD)',
        'chuyen_tiep': 'Quy chuẩn bắt buộc áp dụng khi lập hồ sơ thiết kế BVTC công trình (TV-04, TV-05, XD-01)',
        'tags': 'PCCC, TV-02, TV-03, TV-04, TV-05, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=QCVN%2006%3A2022/BXD'},
    {   'linh_vuc': 'Bảo vệ Môi trường',
        'loai_vb': 'Luật',
        'so_hieu': '72/2020/QH14',
        'trich_yeu': 'Luật Bảo vệ môi trường năm 2020',
        'co_quan': 'Quốc hội',
        'ngay_bh': '17/11/2020',
        'ngay_hl': '01/01/2022',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Bảo vệ môi trường 2014',
        'chuyen_tiep': 'Luật nền tảng về ĐTM, Giấy phép môi trường và Đăng ký môi trường dự án',
        'tags': 'MOI_TRUONG, TV-01, TV-02, TV-03, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=72/2020/QH14'},
    {   'linh_vuc': 'Bảo vệ Môi trường',
        'loai_vb': 'Nghị định',
        'so_hieu': '08/2022/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều của Luật Bảo vệ môi trường',
        'co_quan': 'Chính phủ',
        'ngay_bh': '10/01/2022',
        'ngay_hl': '10/01/2022',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Được sửa đổi, bổ sung bởi Nghị định 05/2025/NĐ-CP và Nghị định 48/2026/NĐ-CP',
        'chuyen_tiep': 'Quy định phân nhóm dự án đầu tư theo tiêu chí môi trường để lập ĐTM hoặc đăng ký môi trường',
        'tags': 'MOI_TRUONG, TV-01, TV-02, TV-03, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=08/2022/N%C4%90-CP'},
    {   'linh_vuc': 'Bảo vệ Môi trường',
        'loai_vb': 'Nghị định',
        'so_hieu': '05/2025/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung một số điều của Nghị định số 08/2022/NĐ-CP về bảo vệ môi trường',
        'co_quan': 'Chính phủ',
        'ngay_bh': '06/01/2025',
        'ngay_hl': '06/01/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi Nghị định 08/2022/NĐ-CP',
        'chuyen_tiep': 'Đơn giản hóa thủ tục cấp giấy phép môi trường và phân cấp thẩm quyền thẩm định ĐTM',
        'tags': 'MOI_TRUONG, TV-01, TV-02, TV-03, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=05/2025/N%C4%90-CP'},
    {   'linh_vuc': 'Bảo vệ Môi trường',
        'loai_vb': 'Nghị định',
        'so_hieu': '48/2026/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung các Nghị định quy định chi tiết Luật Bảo vệ môi trường',
        'co_quan': 'Chính phủ',
        'ngay_bh': '29/01/2026',
        'ngay_hl': '29/01/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi Nghị định 08/2022/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 29/01/2026; bãi bỏ cấp đổi GPMT phức tạp; phân cấp thẩm định ĐTM; cho phép làm '
                       'thủ tục môi trường song song với thiết kế xây dựng',
        'tags': 'MOI_TRUONG, TV-01, TV-02, TV-03, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=48/2026/N%C4%90-CP'},
    {   'linh_vuc': 'Bảo vệ Môi trường',
        'loai_vb': 'Nghị quyết',
        'so_hieu': '66.19/2026/NQ-CP',
        'trich_yeu': 'Nghị quyết tháo gỡ khó khăn trong thực hiện thủ tục môi trường cho dự án đầu tư công',
        'co_quan': 'Chính phủ',
        'ngay_bh': '18/05/2026',
        'ngay_hl': '01/07/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Cơ chế đặc thù tháo gỡ thủ tục đăng ký môi trường đối với dự án cải tạo, sửa chữa doanh trại',
        'tags': 'MOI_TRUONG, TV-01, TV-02, TV-03, TV-04, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=66.19/2026/NQ-CP'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Luật',
        'so_hieu': '15/2017/QH14',
        'trich_yeu': 'Luật Quản lý, sử dụng tài sản công',
        'co_quan': 'Quốc hội',
        'ngay_bh': '21/06/2017',
        'ngay_hl': '01/01/2018',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Quản lý tài sản nhà nước 2008',
        'chuyen_tiep': 'Chế độ quản lý, bảo dưỡng, nâng cấp và sử dụng tài sản công trong các cơ quan, đơn vị',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=15/2017/QH14'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Nghị định',
        'so_hieu': '151/2017/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết một số điều của Luật Quản lý, sử dụng tài sản công',
        'co_quan': 'Chính phủ',
        'ngay_bh': '26/12/2017',
        'ngay_hl': '01/01/2018',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Được sửa đổi, bổ sung bởi Nghị định 114/2024/NĐ-CP và Nghị định 186/2025/NĐ-CP',
        'chuyen_tiep': 'Quy trình sử dụng tài sản công, sửa chữa và bảo dưỡng tài sản',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=151/2017/N%C4%90-CP'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Nghị định',
        'so_hieu': '114/2024/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung một số điều của Nghị định 151/2017/NĐ-CP về quản lý tài sản công',
        'co_quan': 'Chính phủ',
        'ngay_bh': '15/09/2024',
        'ngay_hl': '30/10/2024',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi Nghị định 151/2017/NĐ-CP',
        'chuyen_tiep': 'Phân cấp thẩm quyền bảo dưỡng, sửa chữa tài sản công trong các đơn vị dự toán',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=114/2024/N%C4%90-CP'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Nghị định',
        'so_hieu': '186/2025/NĐ-CP',
        'trich_yeu': 'Sửa đổi, bổ sung Nghị định số 151/2017/NĐ-CP về quản lý, sử dụng tài sản công',
        'co_quan': 'Chính phủ',
        'ngay_bh': '10/06/2025',
        'ngay_hl': '01/08/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Sửa đổi Nghị định 151/2017/NĐ-CP',
        'chuyen_tiep': 'Hướng dẫn cụ thể về trình tự phê duyệt dự toán sửa chữa, cải tạo tài sản công',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=186/2025/N%C4%90-CP'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Nghị định',
        'so_hieu': '104/2026/NĐ-CP',
        'trich_yeu': 'Quy định việc sử dụng kinh phí chi thường xuyên NSNN để mua sắm, cải tạo, sửa chữa tài sản công',
        'co_quan': 'Chính phủ',
        'ngay_bh': '18/03/2026',
        'ngay_hl': '01/05/2026',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 138/2024/NĐ-CP và Nghị định 98/2025/NĐ-CP',
        'chuyen_tiep': 'Có hiệu lực từ 01/05/2026; phân cấp Thủ trưởng đơn vị dự toán BQP phê duyệt dự toán sửa chữa '
                       'cơ sở vật chất, doanh trại dưới 15 tỷ đồng',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=104/2026/N%C4%90-CP'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Nghị định',
        'so_hieu': '138/2024/NĐ-CP',
        'trich_yeu': 'Quy định sử dụng kinh phí chi thường xuyên mua sắm, cải tạo tài sản công (Hết hiệu lực)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '24/10/2024',
        'ngay_hl': '24/10/2024',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 98/2025/NĐ-CP và Nghị định 104/2026/NĐ-CP',
        'chuyen_tiep': 'Đã hết hiệu lực',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=138/2024/N%C4%90-CP'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Nghị định',
        'so_hieu': '98/2025/NĐ-CP',
        'trich_yeu': 'Sửa đổi Nghị định 138/2024/NĐ-CP về sử dụng kinh phí chi thường xuyên (Hết hiệu lực)',
        'co_quan': 'Chính phủ',
        'ngay_bh': '12/05/2025',
        'ngay_hl': '01/07/2025',
        'trang_thai': 'Hết hiệu lực',
        'thay_the': 'Bị thay thế bởi Nghị định 104/2026/NĐ-CP',
        'chuyen_tiep': 'Hết hiệu lực',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, LICHSU',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=98/2025/N%C4%90-CP'},
    {   'linh_vuc': 'Chi thường xuyên & Tài sản công',
        'loai_vb': 'Thông tư',
        'so_hieu': '65/2021/TT-BTC',
        'trich_yeu': 'Quy định về lập dự toán, quản lý, sử dụng và quyết toán kinh phí bảo dưỡng, sửa chữa tài sản '
                     'công',
        'co_quan': 'Bộ Tài chính',
        'ngay_bh': '29/07/2021',
        'ngay_hl': '15/09/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Thông tư 92/2017/TT-BTC',
        'chuyen_tiep': 'Hướng dẫn chi tiết định mức lập dự toán chi thường xuyên sửa chữa cơ sở vật chất, doanh trại',
        'tags': 'CHI_THUONG_XUYEN, TAI_SAN_CONG, SUA_CHUA, TV-01, TV-02, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=65/2021/TT-BTC'},
    {   'linh_vuc': 'Thể thức Văn bản',
        'loai_vb': 'Nghị định',
        'so_hieu': '30/2020/NĐ-CP',
        'trich_yeu': 'Về công tác văn thư',
        'co_quan': 'Chính phủ',
        'ngay_bh': '05/03/2020',
        'ngay_hl': '05/03/2020',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Nghị định 110/2004/NĐ-CP',
        'chuyen_tiep': 'Quy chuẩn thể thức văn bản hành chính (Tờ trình, Quyết định, Biên bản, font Times New Roman '
                       '13pt/14pt)',
        'tags': 'ALL, THE_THUC, TV-01, TV-02, TV-03, TV-04, TV-05, TV-06, TV-07, TV-08, TV-09, PTV-01, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=30/2020/N%C4%90-CP'},
    {   'linh_vuc': 'Đối tác công tư',
        'loai_vb': 'Luật',
        'so_hieu': '64/2020/QH14',
        'trich_yeu': 'Luật Đầu tư theo phương thức đối tác công tư (PPP)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '18/06/2020',
        'ngay_hl': '01/01/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Căn cứ pháp lý cho các dự án đầu tư theo hình thức đối tác công tư',
        'tags': 'PPP, DAU_TU_CONG',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=64/2020/QH14'},
    {   'linh_vuc': 'Đối tác công tư',
        'loai_vb': 'Nghị định',
        'so_hieu': '35/2021/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết và hướng dẫn thi hành Luật Đầu tư theo phương thức đối tác công tư',
        'co_quan': 'Chính phủ',
        'ngay_bh': '29/03/2021',
        'ngay_hl': '29/03/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Quy định chi tiết quy trình lập dự án và lựa chọn nhà đầu tư PPP',
        'tags': 'PPP, DAU_TU_CONG',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=35/2021/N%C4%90-CP'},
    {   'linh_vuc': 'Đầu tư kinh doanh',
        'loai_vb': 'Luật',
        'so_hieu': '61/2020/QH14',
        'trich_yeu': 'Luật Đầu tư năm 2020 (sửa đổi bởi Luật số 57/2024/QH15)',
        'co_quan': 'Quốc hội',
        'ngay_bh': '17/06/2020',
        'ngay_hl': '01/01/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Thay thế Luật Đầu tư 2014',
        'chuyen_tiep': 'Căn cứ pháp lý về thủ tục chấp thuận chủ trương đầu tư dự án',
        'tags': 'DAU_TU_KINH_DOANH',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=61/2020/QH14'},
    {   'linh_vuc': 'Đầu tư kinh doanh',
        'loai_vb': 'Nghị định',
        'so_hieu': '31/2021/NĐ-CP',
        'trich_yeu': 'Quy định chi tiết và hướng dẫn thi hành một số điều của Luật Đầu tư',
        'co_quan': 'Chính phủ',
        'ngay_bh': '26/03/2021',
        'ngay_hl': '26/03/2021',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Quy định chi tiết trình tự, thủ tục đầu tư và ưu đãi đầu tư',
        'tags': 'DAU_TU_KINH_DOANH',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=31/2021/N%C4%90-CP'},
    {   'linh_vuc': 'Quốc phòng & Doanh trại',
        'loai_vb': 'Văn bản Hợp nhất',
        'so_hieu': '15/VBHN-BQP',
        'trich_yeu': 'Văn bản hợp nhất Thông tư quy định về phân cấp, ủy quyền quyết định chủ trương đầu tư và dự án '
                     'đầu tư công trong Bộ Quốc phòng',
        'co_quan': 'Bộ Quốc phòng',
        'ngay_bh': '15/03/2025',
        'ngay_hl': '15/03/2025',
        'trang_thai': 'Đang có hiệu lực',
        'thay_the': 'Văn bản gốc / Ban hành lần đầu',
        'chuyen_tiep': 'Văn bản hợp nhất hướng dẫn công tác quản lý dự án và phân cấp trong Bộ Quốc phòng',
        'tags': 'ALL, BQP, PHAN_CAP, QLDA, TV-01, TV-02, TV-03, TV-04, TV-05, TV-08, XD-01',
        'link_iv': 'https://thuvienphapluat.vn/page/tim-van-ban.aspx?keyword=15/VBHN-BQP'}]

def load_master_seeds(excel_path: str = EXCEL_PATH, reset: bool = True) -> int:
    """Nạp toàn bộ hạt giống pháp lý Master Seed vào file Excel chuẩn 14 cột với giao diện chuẩn."""
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Can_Cu_Phap_Ly"
    ws.append(HEADERS_14)

    for idx, item in enumerate(MASTER_SEED_RECORDS, start=1):
        row_data = [
            idx,
            item["linh_vuc"],
            item["loai_vb"],
            item["so_hieu"],
            item["trich_yeu"],
            item["co_quan"],
            item["ngay_bh"],
            item["ngay_hl"],
            item["trang_thai"],
            item["thay_the"],
            item["chuyen_tiep"],
            item["tags"],
            item.get("link_iv", ""),
            now_str
        ]
        ws.append(row_data)

    apply_table_formatting(ws)

    saved_path = excel_path
    try:
        wb.save(excel_path)
    except PermissionError:
        pending_path = excel_path.replace(".xlsx", "_pending.xlsx")
        wb.save(pending_path)
        saved_path = pending_path
        print(f"[!] CẢNH BÁO: Excel đang mở. Đã lưu tạm an toàn vào: {os.path.basename(pending_path)}")

    wb.close()

    try:
        from modules.web_card_generator import generate_mobile_card_web
        generate_mobile_card_web(excel_path=saved_path)
    except Exception as e:
        print(f"[!] Không thể cập nhật Web Card View: {e}")

    total_records = len(MASTER_SEED_RECORDS)
    print(f"✅ ĐÃ TỔNG HỢP TOÀN BỘ SỔ CÁI EXCEL MỚI: {total_records} văn bản chuẩn 14 cột!")
    return total_records


if __name__ == "__main__":
    total = load_master_seeds()
    print(f"🏛️ Tổng số văn bản trong Sổ cái Master: {total}")
